#!/usr/bin/env bash

# set -x

# we need this in every script
this_script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# set xdg to default location if its undefined
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

# other variables

dry_run=0
filter=""
clean=0

# general functions
function log() {
   GREEN='\033[0;32m'
   NOCOL='\033[0m'
   if [[ $dry_run -eq 1 ]]; then
      printf "${GREEN}[DRY_RUN]${NOCOL} $@\n"
   else 
      printf "$@\n" 
   fi
}

# general functions
function log_error() {
   RED='\033[0;33m'
   NOCOL='\033[0m'
   printf "${RED}[ERROR]${NOCOL}$@\n"
}

function execute() {
   log "Executing: '$@'"
   if [[ $dry_run -eq 1 ]]; then
      return
   fi
   bash -c "$@"
}
# parse parameters

while [[ $# -gt "0" ]]; do
 case "$1" in 
    # switch
    -d|--dry-run)
       dry_run=1
       shift
       ;;
    # parameter
    -f|--filter)
       filter=$2
       shift 2
       ;;
    -c|--clean)
       clean=1
       shift
       ;;
    -h|--help)
       echo "Usage: $0 [-d|--dry-run] [-f|--filter filterword] [-c|--clean]"
       exit 0
       ;;
    *)
   # no more options, break
       break
       ;;
 esac
done

( cd "${this_script_dir}/dotenvs"; \
  for dotenv_name in $(find -mindepth 1 -maxdepth 1 -type d -printf '%P\n'); do
      pushd $dotenv_name
      # expand basedir
      basedir=$(echo "$(cat .basedir)");
      for my_item in $(find  -mindepth 1 -maxdepth 1 ! -name '.basedir' -printf '%P\n'); do
         execute "rm -rf $basedir/$my_item";
         if [[ $clean -eq 0 ]]; then
            execute "cp -r $my_item $basedir";
         fi
      done;
      popd
  done;
)
